### ISSUE TITLE
Tag outputs no data, EE 4.1.3

### ISSUE THREAD

**Issue by bsrweb** [amphibian/time_select.ee_addon#8]
I see the data in the table but the tag doesn't output anything. On line 284 in ft.time_select.php, adding a var_dump() before this line outputs the data but adding a var_dump after this line outputs nothing. In other words

`var_dump($data); //outputs data
	$data = $this->_create_timestamp($data);
var_dump($data); //outputs no data`

Any suggestions? Thank you!

**Comment by bsrweb** [comment]
UPDATE: If I comment-out line #284, `$data = $this->_create_timestamp($data);`, the tag output my data.

**Comment by amphibian** [comment]
This should be fixed now with the latest update.
